//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{

    using System;
    using System.Collections.Generic;

    public partial class Audit
    {
        public int AuditID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ActionType { get; set; }
        public Nullable<System.DateTime> ActionTime { get; set; }
        public string Details { get; set; }

        public virtual UserAccount UserAccount { get; set; }
    }
}
